name: deploy na aws

on:
  push:
    branches:
      - development
      - staging
      - production

jobs:
  run_deploy:
    uses: ./terraform.yml
    with:
      environment: ${{ github.ref_name }}
    secrets: inherit